name: "Release"

on:
  push:
    branches: [ "master", base ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup git
        run: |
          git config --global user.email "313227220@qq.com"
          git config --global user.name "pangzixiang"
          git config --global user.password "${{ secrets.service_password }}"

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Release Maven package
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ secrets.gpg_private_key }}
          gpg_passphrase: ${{ secrets.gpg_passphrase }}
          nexus_username: ${{ secrets.nexus_username }}
          nexus_password: ${{ secrets.nexus_password }}
          maven_goals_phases: "--batch-mode clean release:prepare release:perform"
